# Generated by Django 5.1.1 on 2024-11-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dcatz', '0002_allfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item_name', models.CharField(max_length=2054)),
                ('cart_file_name', models.CharField(max_length=2054)),
                ('cart_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='allfiles',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
