# Generated by Django 5.1.1 on 2024-11-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dcatz', '0003_cartitems_alter_allfiles_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=2054)),
                ('item_name', models.CharField(max_length=2054)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
