# Generated by Django 5.0.2 on 2024-12-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dcatz", "0006_alter_userprofile_address_alter_userprofile_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="barangay",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="province",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
