# Generated by Django 5.1.1 on 2024-11-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dcatz', '0006_alter_userprofile_address_alter_userprofile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataccessories',
            name='description',
            field=models.CharField(max_length=2054, null=True),
        ),
    ]
