# Generated by Django 5.1.1 on 2024-11-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dcatz', '0007_cataccessories_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cataccessories',
            name='description',
            field=models.TextField(max_length=2054, null=True),
        ),
    ]
