# Generated by Django 5.1.1 on 2024-11-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dcatz', '0008_alter_cataccessories_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='varieties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety_name', models.CharField(max_length=2054)),
                ('variety_image', models.ImageField(upload_to='static/varieties')),
            ],
        ),
    ]
