# Generated by Django 5.1.1 on 2024-11-27 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dcatz', '0009_varieties'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfiles',
            name='description',
            field=models.TextField(max_length=2054, null=True),
        ),
        migrations.AddField(
            model_name='allfiles',
            name='file_image',
            field=models.ImageField(null=True, upload_to='static/varieties'),
        ),
        migrations.AddField(
            model_name='varieties',
            name='variety',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dcatz.allfiles'),
        ),
    ]
