# Generated by Django 5.1.1 on 2024-11-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dcatz', '0010_allfiles_description_allfiles_file_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfiles',
            name='file_image',
            field=models.ImageField(null=True, upload_to='static/all-files'),
        ),
    ]
