# Generated by Django 5.1.1 on 2024-11-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dcatz', '0011_alter_allfiles_file_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfiles',
            name='category',
            field=models.CharField(max_length=2054, null=True),
        ),
    ]
