# Generated by Django 5.1.1 on 2024-11-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dcatz', '0012_allfiles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='varieties',
            name='variety_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='allfiles',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Clothing', 'Clothing'), ('Food', 'Food'), ('Furniture', 'Furniture'), ('Toys', 'Toys')], max_length=2054, null=True),
        ),
    ]
