# Generated by Django 5.1.1 on 2024-11-27 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dcatz', '0013_varieties_variety_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cataccessories',
            name='description',
        ),
        migrations.AddField(
            model_name='cataccessories',
            name='information',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dcatz.allfiles'),
        ),
    ]
